package oops_Concept.encapsulation_learning;

/*  Encapsulation / data hiding
Getters and setters in Java are used to control how code outside a class reads and updates that class’s fields,
which helps enforce encapsulation, validation, and future flexibility of the class design.

Core idea
- A getter returns the value of a private field (also called an accessor).
- A setter changes the value of a private field (also called a mutator)
 */

public class encapsulation_invoking_getters_setters {

    public static void main(String[] arg){

        encapsulation_getters_setters_example_manual objMan = new encapsulation_getters_setters_example_manual();
        objMan.setEmployeeNum(535232); //setting a value
        System.out.println(objMan.getEmployeeNum()); //getting the value

        encapsulation_getters_setters_example_autoGenerated objAuto= new encapsulation_getters_setters_example_autoGenerated();
        objAuto.setEmployeeNum(98765); //setting a value
        System.out.println(objAuto.getEmployeeNum()); //getting the value


    }
}
