package oops_Concept.encapsulation_learning;

/*
Autogenerate Getters and Setters : Code -> Generate
 */
public class encapsulation_getters_setters_example_autoGenerated {

    private int EmployeeNum; // Class variable

    public int getEmployeeNum() {
        return EmployeeNum;
    }

    public void setEmployeeNum(int employeeNum) {
        EmployeeNum = employeeNum;
    }



}
